name: Link-check
on:
  schedule:
    - cron: '0 0 * * 1'  # every monday
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run linksafe
        uses: TechWiz-3/linksafe@fast
        with:
          whitelist_links: "http://www.clamav.net/,https://www.cipherdyne.org/fwknop/,http://bruteforce.gr/honeydrive,https://ossec.github.io/"
        env:
          TOKEN: ${{ secrets.TOKEN }}
        
